import CareCategory from './CareCategory';

// 소분류 치료 분야
export enum CareArea {
  // 눈 주변
  EYEAREA_DARKCIRCLES = 'EYEAREA_DARKCIRCLES',
  EYEAREA_UNDEREYEHOLLOWS = 'EYEAREA_UNDEREYEHOLLOWS',
  EYEAREA_WRINKLES = 'EYEAREA_WRINKLES',

  // 입가/표정
  MOUTHAREA_WRINKLES = 'MOUTHAREA_WRINKLES',
  MOUTHAREA_NASOLABIALFOLDS = 'MOUTHAREA_NASOLABIALFOLDS',
  MOUTHAREA_PERIORALWRINKLES = 'MOUTHAREA_PERIORALWRINKLES',

  // 턱선/하안면
  JAWLINE_SAGGING = 'JAWLINE_SAGGING',
  JAWLINE_DOUBLECHIN = 'JAWLINE_DOUBLECHIN',
  JAWLINE_SQUAREJAW = 'JAWLINE_SQUAREJAW',

  // 피부 볼륨 · 구조
  VOLUMESTRUCTURE_FACEVOLUME = 'VOLUMESTRUCTURE_FACEVOLUME',
  VOLUMESTRUCTURE_CHEEKHOLLOWS = 'VOLUMESTRUCTURE_CHEEKHOLLOWS',
  VOLUMESTRUCTURE_TEMPLEHOLLOWS = 'VOLUMESTRUCTURE_TEMPLEHOLLOWS',
  VOLUMESTRUCTURE_UNDEREYEHOLLOWS = 'VOLUMESTRUCTURE_UNDEREYEHOLLOWS',
  VOLUMESTRUCTURE_FLATFACE = 'VOLUMESTRUCTURE_FLATFACE',

  // 피부 탄력 · 결
  SKINELASTICITY_LOSSOFELASTICITY = 'SKINELASTICITY_LOSSOFELASTICITY',
  SKINELASTICITY_FINEWRINKLES = 'SKINELASTICITY_FINEWRINKLES',
  SKINELASTICITY_SAGGING = 'SKINELASTICITY_SAGGING',
  SKINELASTICITY_THINSKIN = 'SKINELASTICITY_THINSKIN',

  // 톤 · 인상
  SKINTONE_DULLSKIN = 'SKINTONE_DULLSKIN',
  SKINTONE_LACKOFRADIANCE = 'SKINTONE_LACKOFRADIANCE',
  SKINTONE_ROUGHSKIN = 'SKINTONE_ROUGHSKIN',

  // 여드름 흔적
  ACNESCAR_SCARS = 'ACNESCAR_SCARS',
  ACNESCAR_PITSCARS = 'ACNESCAR_PITSCARS',
  ACNESCAR_REDNESS = 'ACNESCAR_REDNESS',
  ACNESCAR_PIGMENTATION = 'ACNESCAR_PIGMENTATION',

  // 모공 · 결
  PORETEXTURE_ENLARGEDPORES = 'PORETEXTURE_ENLARGEDPORES',
  PORETEXTURE_SAGGEDPORES = 'PORETEXTURE_SAGGEDPORES',
  PORETEXTURE_VISIBLEPORES = 'PORETEXTURE_VISIBLEPORES',
  PORETEXTURE_UNEVENTEXTURE = 'PORETEXTURE_UNEVENTEXTURE',

  // 피부 민감 · 회복
  SKINSENSITIVITY_DRYSKIN = 'SKINSENSITIVITY_DRYSKIN',
  SKINSENSITIVITY_BARRIERWEAKNESS = 'SKINSENSITIVITY_BARRIERWEAKNESS',
  SKINSENSITIVITY_SENSITIZED = 'SKINSENSITIVITY_SENSITIZED',
  SKINSENSITIVITY_SLOWRECOVERY = 'SKINSENSITIVITY_SLOWRECOVERY',

  // 모발 · 두피
  HAIRSCALP_HAIRLOSS = 'HAIRSCALP_HAIRLOSS',
  HAIRSCALP_THINNINGHAIR = 'HAIRSCALP_THINNINGHAIR',
  HAIRSCALP_BALDCROWN = 'HAIRSCALP_BALDCROWN',
  HAIRSCALP_RECEDINGHAIRLINE = 'HAIRSCALP_RECEDINGHAIRLINE',
  HAIRSCALP_WEAKSCALP = 'HAIRSCALP_WEAKSCALP',

  // 바디 상체 · 중심
  BODYUPPER_BELLYFAT = 'BODYUPPER_BELLYFAT',
  BODYUPPER_LOVEHANDLES = 'BODYUPPER_LOVEHANDLES',
  BODYUPPER_WAISTLINE = 'BODYUPPER_WAISTLINE',
  BODYUPPER_BACKFAT = 'BODYUPPER_BACKFAT',
  BODYUPPER_BRALINEFAT = 'BODYUPPER_BRALINEFAT',

  // 바디 힙 · 하체
  BODYLOWER_SAGGINGHIP = 'BODYLOWER_SAGGINGHIP',
  BODYLOWER_HIPVOLUME = 'BODYLOWER_HIPVOLUME',
  BODYLOWER_INNERTHIGH = 'BODYLOWER_INNERTHIGH',
  BODYLOWER_OUTERTHIGH = 'BODYLOWER_OUTERTHIGH',
  BODYLOWER_ABOVEKNEE = 'BODYLOWER_ABOVEKNEE',
  BODYLOWER_CALFLINE = 'BODYLOWER_CALFLINE',

  // 바디 탄력 · 처짐
  BODYELASTICITY_LOSSOFELASTICITY = 'BODYELASTICITY_LOSSOFELASTICITY',
  BODYELASTICITY_LOOSESKIN = 'BODYELASTICITY_LOOSESKIN',
  BODYELASTICITY_POSTPARTUM = 'BODYELASTICITY_POSTPARTUM',
  BODYELASTICITY_WEIGHTCHANGE = 'BODYELASTICITY_WEIGHTCHANGE',

  // 바디 체형 · 비율
  BODYSHAPE_PROPORTION = 'BODYSHAPE_PROPORTION',
  BODYSHAPE_BULKY = 'BODYSHAPE_BULKY',
  BODYSHAPE_PELVICLINE = 'BODYSHAPE_PELVICLINE',

  // 전체 인상
  OVERALLIMPRESSION_TIRED = 'OVERALLIMPRESSION_TIRED',
  OVERALLIMPRESSION_AGED = 'OVERALLIMPRESSION_AGED',
  OVERALLIMPRESSION_DULL = 'OVERALLIMPRESSION_DULL',
  OVERALLIMPRESSION_NOTMYSELF = 'OVERALLIMPRESSION_NOTMYSELF',
  OVERALLIMPRESSION_NATURALIMPROVEMENT = 'OVERALLIMPRESSION_NATURALIMPROVEMENT',
}

export namespace CareArea {
  const labels: Record<CareArea, string> = {
    // 눈 주변
    [CareArea.EYEAREA_DARKCIRCLES]: '다크서클',
    [CareArea.EYEAREA_UNDEREYEHOLLOWS]: '눈 밑 꺼짐',
    [CareArea.EYEAREA_WRINKLES]: '눈가 잔주름',

    // 입가/표정
    [CareArea.MOUTHAREA_WRINKLES]: '입가 주름',
    [CareArea.MOUTHAREA_NASOLABIALFOLDS]: '팔자 주름',
    [CareArea.MOUTHAREA_PERIORALWRINKLES]: '입 주변 잔주름',

    // 턱선/하안면
    [CareArea.JAWLINE_SAGGING]: '턱선 처짐',
    [CareArea.JAWLINE_DOUBLECHIN]: '이중턱',
    [CareArea.JAWLINE_SQUAREJAW]: '사각턱',

    // 피부 볼륨 · 구조
    [CareArea.VOLUMESTRUCTURE_FACEVOLUME]: '얼굴 볼륨 감소',
    [CareArea.VOLUMESTRUCTURE_CHEEKHOLLOWS]: '볼 꺼짐',
    [CareArea.VOLUMESTRUCTURE_TEMPLEHOLLOWS]: '관자 꺼짐',
    [CareArea.VOLUMESTRUCTURE_UNDEREYEHOLLOWS]: '눈 밑 꺼짐',
    [CareArea.VOLUMESTRUCTURE_FLATFACE]: '얼굴이 평평해 보임',

    // 피부 탄력 · 결
    [CareArea.SKINELASTICITY_LOSSOFELASTICITY]: '피부 탄력 저하',
    [CareArea.SKINELASTICITY_FINEWRINKLES]: '잔주름 증가',
    [CareArea.SKINELASTICITY_SAGGING]: '피부 처짐',
    [CareArea.SKINELASTICITY_THINSKIN]: '피부가 얇아진 느낌',

    // 톤 · 인상
    [CareArea.SKINTONE_DULLSKIN]: '피부가 칙칙해 보임',
    [CareArea.SKINTONE_LACKOFRADIANCE]: '생기 없는 피부톤',
    [CareArea.SKINTONE_ROUGHSKIN]: '피부가 거칠어 보임',

    // 여드름 흔적
    [CareArea.ACNESCAR_SCARS]: '여드름 흉터',
    [CareArea.ACNESCAR_PITSCARS]: '패인 흉터',
    [CareArea.ACNESCAR_REDNESS]: '붉은 자국',
    [CareArea.ACNESCAR_PIGMENTATION]: '색소 자국',

    // 모공 · 결
    [CareArea.PORETEXTURE_ENLARGEDPORES]: '넓어진 모공',
    [CareArea.PORETEXTURE_SAGGEDPORES]: '늘어진 모공',
    [CareArea.PORETEXTURE_VISIBLEPORES]: '모공이 도드라져 보임',
    [CareArea.PORETEXTURE_UNEVENTEXTURE]: '피부결이 고르지 않음',

    // 피부 민감 · 회복
    [CareArea.SKINSENSITIVITY_DRYSKIN]: '피부 건조',
    [CareArea.SKINSENSITIVITY_BARRIERWEAKNESS]: '피부 장벽 약화',
    [CareArea.SKINSENSITIVITY_SENSITIZED]: '민감해진 피부',
    [CareArea.SKINSENSITIVITY_SLOWRECOVERY]: '시술 후 회복이 느림',

    // 모발 · 두피
    [CareArea.HAIRSCALP_HAIRLOSS]: '탈모',
    [CareArea.HAIRSCALP_THINNINGHAIR]: '모발 가늘어짐',
    [CareArea.HAIRSCALP_BALDCROWN]: '정수리 비어 보임',
    [CareArea.HAIRSCALP_RECEDINGHAIRLINE]: '헤어라인 후퇴',
    [CareArea.HAIRSCALP_WEAKSCALP]: '두피 힘 없음',

    // 바디 상체 · 중심
    [CareArea.BODYUPPER_BELLYFAT]: '복부 지방',
    [CareArea.BODYUPPER_LOVEHANDLES]: '옆구리 군살',
    [CareArea.BODYUPPER_WAISTLINE]: '허리 라인 흐려짐',
    [CareArea.BODYUPPER_BACKFAT]: '등살',
    [CareArea.BODYUPPER_BRALINEFAT]: '브라 라인 군살',

    // 바디 힙 · 하체
    [CareArea.BODYLOWER_SAGGINGHIP]: '힙 처짐',
    [CareArea.BODYLOWER_HIPVOLUME]: '힙 볼륨 감소',
    [CareArea.BODYLOWER_INNERTHIGH]: '허벅지 안쪽 살',
    [CareArea.BODYLOWER_OUTERTHIGH]: '허벅지 바깥 살',
    [CareArea.BODYLOWER_ABOVEKNEE]: '무릎 위 군살',
    [CareArea.BODYLOWER_CALFLINE]: '종아리 라인',

    // 바디 탄력 · 처짐
    [CareArea.BODYELASTICITY_LOSSOFELASTICITY]: '바디 탄력 저하',
    [CareArea.BODYELASTICITY_LOOSESKIN]: '늘어진 살',
    [CareArea.BODYELASTICITY_POSTPARTUM]: '출산 후 바디 변화',
    [CareArea.BODYELASTICITY_WEIGHTCHANGE]: '급격한 체중 변화 후 처짐',

    // 바디 체형 · 비율
    [CareArea.BODYSHAPE_PROPORTION]: '상·하체 비율 불균형',
    [CareArea.BODYSHAPE_BULKY]: '체형이 둔해 보임',
    [CareArea.BODYSHAPE_PELVICLINE]: '골반 라인 불균형',

    // 전체 인상
    [CareArea.OVERALLIMPRESSION_TIRED]: '피곤해 보이는 인상',
    [CareArea.OVERALLIMPRESSION_AGED]: '나이 들어 보이는 느낌',
    [CareArea.OVERALLIMPRESSION_DULL]: '생기 없어 보임',
    [CareArea.OVERALLIMPRESSION_NOTMYSELF]: '예전의 나 같지 않음',
    [CareArea.OVERALLIMPRESSION_NATURALIMPROVEMENT]: '자연스럽게 좋아지고 싶음',
  };

  export function getLabel(area: CareArea): string {
    return labels[area];
  }

  export function getCareCategory(area: CareArea): CareCategory {
    // '_' 앞부분 추출 (예: 'EYEAREA_DARKCIRCLES' -> 'EYEAREA')
    const prefix = area.split('_')[0];
    return prefix as CareCategory;
  }

  export function getCareAreaByCareCategory(careCategory: CareCategory): CareArea[] {
    return (Object.values(CareArea) as string[]).filter(area => area.startsWith(careCategory));
  }
}

export default CareArea;
